---
- hosts: vms
  become: true
  tasks:
    - name: Завершение сеанса за бездействие (25)
      block:
        # Надо добавить поверку на ТУЗ
        - name: Добавлене переменной окружения
          lineinfile:
            path: /etc/profile
            regexp: "^export TMOUT="
            line: export TMOUT=900
            insertafter: EOF
            backup: true
          
        - name: Перезагрузка сессии
          shell: source /etc/profile

    # Дективация после 90 дней бездействия
    - name: Деактивация неактивных УЗ (27)
      block:            
        - name: Для УЗ 90 дней
          command: chage --inactive 90 other

        - name: ТУЗ нельзя деактивировать
          command: chage --inactive -1 tuz
