---
- hosts: vms
  become: true
  tasks:
    - name: (1, 4, 7, 8, 190, 191)
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "^minlen=", line: "minlen=16" } # (1)
        - { regexp: "^dcredit=", line: "dcredit=-1" } # (4)
        - { regexp: "^ucredit=", line: "ucredit=-1" } # (4)
        - { regexp: "^ocredit=", line: "ocredit=-1" } # (4)
        - { regexp: "^lcredit=", line: "lcredit=-1" } # (4)
        - { regexp: "^maxrepeat=", line: "maxrepeat=2" } # (7)
        - { regexp: "^difok=", line: "difok=6" } # (8)
        - { regexp: "^gecoscheck=", line: "gecoscheck=1" } # (190)
        - { regexp: "^usercheck=", line: "usercheck=1" } # (191)

    - name: (18 + 20, 57)
      vars:
        files:
          - /etc/pam.d/password-auth
          - /etc/pam.d/system-auth
      block:
        - name: Установить deny=6 и unlock_time=1800
          lineinfile:
            path: "{{ item }}"
            regexp: '^auth\s+required\s+pam_faillock\.so\s+preauth'
            line: 'auth        required      pam_faillock.so preauth silent audit deny=6 unlock_time=1800'
            backup: yes
          loop: "{{ files }}" 

        - name: Установить deny=6 и unlock_time=1800
          lineinfile:
            path: "{{ item }}"
            regexp: '^auth\s+\[default=die\]\s+pam_faillock\.so\s+authfail'
            line: 'auth        [default=die] pam_faillock.so authfail audit deny=6 unlock_time=1800'
            backup: yes
          loop: "{{ files }}"

        - name: Обеспечить наличие account required pam_faillock.so
          lineinfile:
            path: "{{ item }}"
            regexp: '^account\s+required\s+pam_faillock\.so'
            line: 'account     required      pam_faillock.so'
            insertbefore: '^account\s+required\s+pam_unix\.so'
            backup: yes
          loop: "{{ files }}"

        - name: Настроить использование sha512 для шифрования паролей в system-auth и password-auth (57)
          lineinfile:
            path: "{{ item }}"
            regexp: '^password\s+sufficient\s+pam_unix\.so'
            line: 'password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok'
            backup: yes
          loop: "{{ files }}"

    - name: Автоматическая плановая смена паролей (22)
      block:
        - name: Для пользовательских УЗ 180 дней
          command: chage -M 180 other
        
        - name: Для административных УЗ 90 дней
          command: chage -M 90 config
        
        - name: Для ТУЗ 99999 дней
          command: chage -M 99999 tuz

    - name: Минимальной срок действия пароля (23)
      lineinfile:
        path: /etc/login.defs
        regex: '^PASS_MIN_DAYS='
        line: 'PASS_MIN_DAYS=7'
