---
- hosts: vms
  become: true
  tasks:
    - name: Минимальный размер пароля - 16 симолов (1)
      lineinfile:
        path: /etc/security/pwquality.conf
        regex: '^minlen='
        line: 'minlen=16'

    - name: Группы симоволов (4)
      block:
        - name: Хотя бы одно число
          lineinfile:
            path: /etc/security/pwquality.conf
            regexp: '^dcredit='
            line: 'dcredit=-1'

        - name: Хотя бы один символ в верхнем регистре
          lineinfile:
            path: /etc/security/pwquality.conf
            regexp: '^ucredit='
            line: 'ucredit=-1'

        - name: Хотя бы один символ в нижнем регистре
          lineinfile:
            path: /etc/security/pwquality.conf
            regexp: '^ocredit='
            line: 'ocredit=-1'

        - name: Хотя бы один спец. символ
          lineinfile:
            path: /etc/security/pwquality.conf
            regexp: '^lcredit='
            line: 'lcredit=-1'

    - name: Не более 2х одинаковых сисмволов подряд (7)
      lineinfile:
        path: /etc/security/pwquality.conf
        regex: '^maxrepeat='
        line: 'maxrepeat=2'

    - name: Отличие нового и старого паролей на 6 символов (8)
      lineinfile:
        path: /etc/security/pwquality.conf
        regex: '^difok='
        line: 'difok=6'

    - name: Повторное использоваие пароля только после 10 смен (11)
      block:
        - name: сохранение 10 последних паролей в системе
          lineinfile:
            path: /etc/pam.d/system-auth
            regexp: '^password\s+required\s+pam_pwhistory\.so'
            line: 'password    required    pam_pwhistory.so remember=10 use_authtok'
            backup: true

        - name: сохранение 10 последних паролей в системе
          lineinfile:
            path: /etc/pam.d/password-auth
            regexp: '^password\s+required\s+pam_pwhistory\.so'
            line: 'password    required    pam_pwhistory.so remember=10 use_authtok'
            backup: true

    - name: (18 + 20)
      block:
      - name: Установить deny=6 и unlock_time=1800 в password-auth
        lineinfile:
              path: /etc/pam.d/password-auth
              regexp: '^auth\s+required\s+pam_faillock\.so\s+preauth'
              line: 'auth        required      pam_faillock.so preauth silent audit deny=6 unlock_time=1800'
              backup: yes

      - name: Установить deny=6 и unlock_time=1800 в password-auth
        lineinfile:
          path: /etc/pam.d/password-auth
          regexp: '^auth\s+\[default=die\]\s+pam_faillock\.so\s+authfail'
          line: 'auth        [default=die] pam_faillock.so authfail audit deny=6 unlock_time=1800'
          backup: yes

      - name: Обеспечить наличие account required pam_faillock.so в password-auth
        lineinfile:
          path: /etc/pam.d/password-auth
          regexp: '^account\s+required\s+pam_faillock\.so'
          line: 'account     required      pam_faillock.so'
          insertbefore: '^account\s+required\s+pam_unix\.so'
          backup: yes

      - name: Установить deny=6 и unlock_time=1800 в system-auth
        lineinfile:
          path: /etc/pam.d/system-auth
          regexp: '^auth\s+required\s+pam_faillock\.so\s+preauth'
          line: 'auth        required      pam_faillock.so preauth silent audit deny=6 unlock_time=1800'
          backup: yes

      - name: Установить deny=6 и unlock_time=1800 в system-auth
        lineinfile:
          path: /etc/pam.d/system-auth
          regexp: '^auth\s+\[default=die\]\s+pam_faillock\.so\s+authfail'
          line: 'auth        [default=die] pam_faillock.so authfail audit deny=6 unlock_time=1800'
          backup: yes

      - name: Обеспечить наличие account required pam_faillock.so в system-auth
        lineinfile:
          path: /etc/pam.d/system-auth
          regexp: '^account\s+required\s+pam_faillock\.so'
          line: 'account     required      pam_faillock.so'
          insertbefore: '^account\s+required\s+pam_unix\.so'
          backup: yes
    
    - name: Автоматическая плановая смена паролей (22)
      block:
        - name: Для пользовательских УЗ 180 дней
          command: chage -M 180 other
        
        - name: Для административных УЗ 90 дней
          command: chage -M 90 config
        
        - name: Для ТУЗ 99999 дней
          command: chage -M 99999 tuz
    
    # 7 дней
    - name: Минимальной срок действия пароля (23)
      lineinfile:
        path: /etc/login.defs
        regex: '^PASS_MIN_DAYS='
        line: 'PASS_MIN_DAYS=7'
        
    - name: Настроить использование sha512 для шифрования паролей в system-auth и password-auth (57)
      block:
      - name: system-auth
        lineinfile:
          path: /etc/pam.d/system-auth
          regexp: '^password\s+sufficient\s+pam_unix\.so'
          line: 'password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok'
          backup: yes

      - name: password-auth
        lineinfile:
          path: /etc/pam.d/password-auth
          regexp: '^password\s+sufficient\s+pam_unix\.so'
          line: 'password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok'
          backup: yes

      - name: Включить проверку поля GECOS (190)
        lineinfile:
          path: /etc/security/pwquality.conf
          regexp: '^gecoscheck='
          line: 'gecoscheck=1'

      - name: Включить проверку имени учетной записи (191)
        lineinfile:
          path: /etc/security/pwquality.conf
          regexp: '^usercheck='
          line: 'usercheck=1'
