---
- hosts: vms
  become: true
  tasks:
    - name: Синхронизация системного времени (34)
      vars:
        file: /etc/chrony.conf
      block:
        - name: Установка пакета chrony
          package:
            name: chrony
            state: present

        - name: Отключение предустановленных серверов
          lineinfile:
            path: "{{ file }}"
            regexp: '^server '
            state: absent

        - name: Установка новых серверов
          vars:
            # Серваки яндекса?
            ntp_servers:
              - 0.ru.pool.ntp.org
              - 1.ru.pool.ntp.org
              - ntp2.vniiftri.ru
              - ntp.ix.ru
          lineinfile:
            path: "{{ file }}"
            line: 'server {{ item }} iburst'
            insertbefore: 'BOF'
          loop: '{{ ntp_servers }}'

        - name: Перезапуск сервера
          service:
            name: chronyd
            state: restarted
            enabled: true

    - name: Защита от несанкционированного доступа (36)
      command: update-crypto-policies --set DEFAULT

    - name: Шифрование канала (166)
      block:
        - name: Создание копии файла
          copy:
            remote_src: true
            src: /etc/crypto-policies/back-ends/opensslcnf.config
            dest: /etc/crypto-policies/back-ends/opensslcnf.config.backup

        # Устанавливаются только TLS
        - name: Ciphersuites
          lineinfile: 
            path: /etc/crypto-policies/back-ends/opensslcnf.config
            regexp: '^Ciphersuites ='
            line: 'Ciphersuites = TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'

        - name: CipherString
          lineinfile:
            path: /etc/crypto-policies/back-ends/opensslcnf.config
            regexp: '^CipherString ='
            line: 'CipherString = SECLEVEL=2'

        - name: SignatureAlgorithms
          lineinfile:
            path: /etc/crypto-policies/back-ends/opensslcnf.config
            regexp: '^SignatureAlgorithms ='
            line: 'SignatureAlgorithms = '
